title: Caren V. Garcia
email: carenvaleria90@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sharing knowledge and empowering individuals
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://carenvaleria.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: carenvaleria
github_username:  carenvaleria

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
